### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by msemikin** [sstur/react-rte#105]
Hello, thank you for the great project.
We use TypeScript in our React app and it would be great to have types support for this package as well.

**Comment by sstur** [comment]
Hi @caliber01. Thanks for using React-RTE.

We use [Flow](https://flowtype.org/) for typing this library (although that shouldn't affect you as a consumer of this package, you're free to use whatever type system you like).

At this time I don't have any plans to add TypeScript related features but I'd be happy to accept a PR to that effect.

**Comment by bherila** [comment]
@caliber01 I am planning on adding typescript definitions now that typescript allows us to include the typings right here in this repo.

**Comment by raliste** [comment]
@bherila I'm looking into the same, do you have them already? Appreciated!

**Comment by bherila** [comment]
I don't have them, I am simply using it untyped.

**Comment by ricokahler** [comment]
@bherila Any progress on typings? I'm also looking to type this library and adding the definitions to DefinitelyTyped. As of April 15th 2018, they aren't there.

@sstur thanks for the awesome drop-in RTE!

Would you be open to a pull request adding those definitions inside this repo (vs on DefinitelyTyped)? If you don't use typescript, it may be better to leave them on DefinitelyTyped but if you do, then it would be better if this repo had them because you'd have control over them.

**Comment by Duckapple** [comment]
Types have been added via the DefinitelyTyped project: https://www.npmjs.com/package/@types/react-rte
I suggest closing this issue for that reason.
