### ISSUE TITLE
Mobile devices- typing bug- cursor jumps around

### ISSUE THREAD

**Issue by yarnball** [sstur/react-rte#124]
Hi,

Great work on this!

On both Chrome and Safari (mobile) the typing seems to get gets very confused. If I use the delete button, the cursor gets lost. It jumps around within the RTE box. Then it stops being able to type at all.

Have I implemented it properly? It works fine on desktop browsers...

```
var ReactRTE =  React.createClass({
  propTypes: {
    onChange: React.PropTypes.func
  },

  getInitialState() {
  return {
    value: RichTextEditor.createValueFromString((this.props.photo && this.props.photo.info && this.props.photo.info[0] && this.props.photo.info[0].text) || '', 'html'),
  };
  },
  onChangeEditor: function(value) {
  this.setState({value});
    if (this.props.onChange) {
        value.toString('html')
    }
  },

  editorUpdate: function(e, putID) {
    e.preventDefault();
     return fetch(DATA_URL + this.props.photo.pk + '/', {
     method: 'PUT',
     body: JSON.stringify({"text": this.state.value._cache.html})
      })
      .then(function(res){ return res.json(); })
      .then(function(data){ alert( JSON.stringify( data ) ) })
  },
  render: function(){
        return (
              <form onSubmit={this.editorUpdate}>
            <RichTextEditor
               value={this.state.value}
               onChange={this.onChangeEditor}
               />
               <Button type="submit">Save</Button>
               </form>
        );
    }
})
```

**Comment by sstur** [comment]
There are a few errors in your code above, but nothing that should cause this to work on desktop and not on mobile.

I'd suggest you do NOT stringify the value on every change (line 16) especially since you're not using that string anywhere. On line 22 you should probably not use `_cache.html` since that's a private variable. Use `toString('html')`. A few minor things, `putID` on line 18 will be undefined but I think you're not using it anyway.

Honestly I don't know why it's not working on mobile. I haven't extensively tested on mobile but there have not really been other issues around that.

**Comment by yarnball** [comment]
Thanks!

It seems to happen when the text box area itself doesn't auto expand. I have to add the padding by typing in that area (or pressing return). Maybe adding extra padding could fix this issue?
