### ISSUE TITLE
[Bug]Toobar can't be none

### ISSUE THREAD

**Issue by NE-SmallTown** [sstur/react-rte#205]
When I set `toolbarConfig={{ display: [] }}`, there still exists the toolbar and its style affect the UI.Could you remove the toolbar when I set it to `null` or `[]`?Thanks.

**Comment by NE-SmallTown** [comment]
@gauravchl And could you please tell what this repo does to make the css modules work?I don't import the css file in my project,but we can see that the result dist file will import this repo's css.I want to know how this works,thanks!

**Comment by NE-SmallTown** [comment]
Oh,I see,looks like you make us import the dist file of this repo rather than lib.

**Comment by bherila** [comment]
If you are building the CSS with webpack you should import from `'react-rte/lib/RichTextEditor' ` to get the proper webpack-compatible module. If you import only `react-rte` you will get the pre-built webpack bundle which will end up being "double-webpacked." This is the cause of the issue you are experiencing.

**Comment by NE-SmallTown** [comment]
Thanks. But I think you are talking about the second comment rather than first?

**Comment by bherila** [comment]
@NE-SmallTown the CSS file is imported using `require` so webpack is needed in order to properly load that import. It's up to you if you want to use the src/RichTextEditor directly (in that case you need to supply your own webpack config with some css loader) or the pre-built webpack output file (which is a valid JS module itself).
