### ISSUE TITLE
emoji support

### ISSUE THREAD

**Issue by babsonmatt** [sstur/react-rte#21]
Would be great to see this lib have emoji support - any suggestions as to how this might be implemented?

**Comment by simpixelated** [comment]
Would be cool if https://github.com/draft-js-plugins/draft-js-plugins could be incorporated. They have built plugins for Emoji, Stickers, Hashtags, Linkify, Mentions, and Undo. Looks like they currently require the "draft-js-plugins-editor" though. Maybe there's a way for react-rte to accept plugins and the draft-js community (paging @nikgraf) can start to agree on plugin standards.

**Comment by sstur** [comment]
@babsonmatt: This is not a high priority for me at the moment because I haven't yet completed the some basics such as: images, paragraph alignment, text color, etc. I would be open to contributions however I'd prefer if the emoji images are: optional. external resources (so as not to cause the size of this package to increase). resolution independent.

@simpixelated: I'd be keen to explore integratin @nikgraf's draft-js-plugins! Maybe create a separate issue for that.

**Comment by babsonmatt** [comment]
@simpixelated I wasn't aware of draft-js-plugins, thanks for mentioning that
@sstur makes sense - exploring integration with draft-js-plugins would be awesome

**Comment by sstur** [comment]
I'm going to close for now as "not on roadmap".
