### ISSUE TITLE
Cannot run locally: 404 page for /demo

### ISSUE THREAD

**Issue by thebritican** [sstur/react-rte#31]
After trying node versions `5.10`, `4.2`, `0.12`, I cannot run react-rte locally.

#### steps to reproduce
`npm i`
`npm run build-demo` <- outdated (does not work) and i saw that all the builds were happening anyways
`npm i -g serv`
`serv`

I hacked my way to a solution by modifying the webpack config and creating a `server.js` file like in https://github.com/gaearon/react-hot-boilerplate.

Is there something simple I'm missing? Thanks for the awesome work though!

**Comment by sstur** [comment]
Hey @thebritican. Sorry for the delay. This is a problem I've known about and been meaning to send a PR to `serv` about it. But basically you have to add `.html` on the end of `/demo`. It's that way because I host the `react-rte.org` site on [surge.sh](https://surge.sh) (which is an amazing service). So the public site gets .html automatically added but when running on localhost it doesn't. Sorry about the confusion.

**Comment by sstur** [comment]
I fixed this now (hackily) in the redirect inside `index.html`.
