### ISSUE TITLE
invalid in react 0.14.X?

### ISSUE THREAD

**Issue by beiciye** [sstur/react-rte#44]
Hi !   Must it need react 0.15.X?   We need to support  IE8 in the project.

**Comment by sstur** [comment]
Hi @beiciye. I actually have no issue with supporting react 0.14.x. The reason we bumped it to v15.x was because there were issues in v0.14 with `Warning: A component is 'contentEditable' and contains 'children' managed by React` which was causing some bug reports.

I can probably change the requirement to support v0.14 or v15 but to be honest you will have issues with using this project in IE8 anyway. I doubt draft-js will support versions of IE that old and I have been using Flexbox and similar features that are IE10 and newer.

**Comment by vitosamson** [comment]
In my current project we're not supporting IE8 but we haven't yet made the jump to react v15. It would be really great if you could add 0.14 as a valid peer dependency.

**Comment by beiciye** [comment]
@sstur   I got it . Thank you!

**Comment by beiciye** [comment]
@sstur I have noticed you make a PR to support  images , but I didn't find those files.

**Comment by sstur** [comment]
@beiciye: That question doesn't belong in this issue, the issue you're looking for is #6. It's still a work-in-progress.

**Comment by sstur** [comment]
I updated the package.json to read:
```
  "peerDependencies": {
    "react": "^0.14.0 || ^15.0.1",
    "react-dom": "^0.14.0 || ^15.0.1"
  },
```

Closing this issue. Please re-open if that doesn't fix the issue. Thx.

**Comment by vitosamson** [comment]
Thanks @sstur, could you cut a new version and publish it to npm?

**Comment by sstur** [comment]
Done.
