### ISSUE TITLE
Making a Rich Text Editor flex-ible/full screen

### ISSUE THREAD

**Issue by ralphschindler** [sstur/react-rte#49]
I am attempting to make make use of flexbox in order to build a full screen-ish modal that allows the editing experience to happen in a popup, but also allows the RTE instance to fill a flex column.  Unfortunately, I am not finding a good way to, through the modular css, be able to inject the necessary css in order to achieve the result I am looking for.

(Currently, it appears `.public-DraftEditor-content` is hardcoded to 110px.  But aside from that, it appears I need to modify styles__richTextEditor___2Dl6A RichTextEditor__root___2QXK- which I can't see a way to do.)

Prototype of what I am trying to achieve: https://jsfiddle.net/av0v2540/

Since there is a build process at place that puts a _[hash] in css names, I can't depend on overriding the css inline as it will change from release to release.  What I need to make it achieve the above is the ability to use `display: flex` along with various `flex: 1`, `flex: 2`, and `flex-direction: column` directives. Any insight how I can achieve this with `react-rte` is appreciated.

Thanks in advance.

**Comment by ZeroCho** [comment]
+1
Now, as of 0.1.17, hardcoded 110px disappeared. However, because there is no specific height set to the editor, textarea gets longer and longer without any limit. And if textarea gets longer than the screen's height, toolbar goes up and then, I need to scroll up to click the toolbar buttons and scroll down again to type. It's very uncomfortable.
I really hope that @ralphschindler 's suggestion is reflected.
Sorry for my bad english :)

**Comment by sstur** [comment]
Hi @ralphschindler, sorry for the silence on this issue, I've got a bunch to reply to. I think it's totally reasonable to make this use Flexbox. In fact, I had a branch experimenting with this idea some point but never landed it in master. The idea would be to make it so you can set a height or flex on the main element and all the child elements would fall into line accordingly. As long as we can support IE 10+, I'm happy.

Alternatively, I'm happy to support props that specify `className`'s to be added to the relevant child elements. A PR to this effect would be fine and that will get you past the issue with CSS Modules using "private" class names. Already, you can specify a className to the main `<RichTextEditor />` which will be honored (latest). Then the child elements might be targetable since draft-js doesn't use CSS Modules.

**Comment by ralphschindler** [comment]
Fantastic, I'll fork and work on the idea of passing in classNames to add to the children, that seems to be the most relevant and straight forward approach I think.  That way I can opt-into using flexbox in my design without impacting the more common usage stories out there.

**Comment by sstur** [comment]
I'm going to close this. If you want to open an issue to track the className feature, I'm fine with that..
