### ISSUE TITLE
Found a bug In Image Support

### ISSUE THREAD

**Issue by legendweny** [sstur/react-rte#79]
I‘m going to upload a image
![screen shot 2016-07-14 at 13 26 00](https://cloud.githubusercontent.com/assets/8153838/16828934/ffd9edae-49c6-11e6-9160-27fb29b6f9bc.png)
than copy the HTML
put HTML Into the textarea (it will call the fn ’stateFromHTML‘）
and I got this 
![screen shot 2016-07-14 at 13 26 07](https://cloud.githubusercontent.com/assets/8153838/16828952/4480655a-49c7-11e6-8335-1d5386c9a7b0.png)

so I'm fixed it in ImageSpan.js
` return (
      <span
        className={className}
        style={imageStyle}
        onClick={this._onClick}
      >
          <span style={{opacity:'0'}}>
            {this.props.children}
          </span>
      </span>
    );`
![screen shot 2016-07-14 at 13 26 15](https://cloud.githubusercontent.com/assets/8153838/16829004/aa337a5e-49c7-11e6-9f67-79bbedb0c866.png)

**Comment by ZeroCho** [comment]
@legendweny why dont you make a pull request to my fork package [react-rte-image](https://npmjs.com/package/react-rte-image)? I also use image feature and experience same problem.

**Comment by sstur** [comment]
Hi @legendweny. @ZeroCho is right. This packages does not support images yet : (

I assume you are either running an experimental branch of this repo or using [react-rte-image](https://npmjs.com/package/react-rte-image).

As for this package, my (and others) work is incomplete and not ready, so I'd expect to see bugs such as that one. Please follow #6 for any updates to official image support.

@ZeroCho: I have not been diligent about getting that feature into this package because I've been busy but I'd like to get it in within the next few weeks. I'm curious to hear about your experience with adding image support to your fork. DM me on draftjs slack channel if you are keen to discuss.

**Comment by cfkenandy** [comment]
I'm using v0.5.1 and see the giant tilde but setting the opacity to 0 as shown above solves the problem. Any plans to have a new version out with this fix?

**Comment by ZeroCho** [comment]
@cfkenandy @legendweny you will not see giant tilde anymore with react-rte-image 0.9.0
