### ISSUE TITLE
Feature request: use the toolbar for adding markdown to text

### ISSUE THREAD

**Issue by mshick** [sstur/react-rte#91]
When I first saw the Markdown toggle I thought maybe the editor fully supported both approaches to writing. Unfortunately I discovered the toolbar didn't aid in writing markdown code, i.e., clicking the `B` on selected text would cause the editor to wrap the text in `**`;

I'm fairly new to Draft.js and would certainly be willing to explore submitting  a PR, but could definitely use guidance on whether this is even possible. Draft.js seems very flexible, and I imagine there must be a way to modify how the Editor component represents and modifies the state. 

I've tried modifying the `RichTextEditor.js` in the source here with a custom `blockRenderFn` and custom `CompositeDecorator`s, to pretty weird results, and little comprehension... Ultimately what I imagine I need is a hook into the state of the editor content where I could, say, choose how I would render into the edit area a block flagged as BOLD via `RichUtils.toggleInlineStyle`, and then of course would be able to interpret those asterisks when the whole string was highlighted, to toggle BOLD off.

**Comment by sstur** [comment]
Hi @mshick. I'm not sure I fully understand you question, but I will try to address what I think you're asking.

This editor is specifically for creating content using a rich-text style composer, implemented as a `contentEditable` element in the browser. This project is not designed to assist manually writing source code (html/markdown/etc). It simply \*outputs\* source code (and conversely can populate the editor from source code).

There are other projects out there designed assist you writing Markdown \*source\* (like the editor I'm typing in now) but that's not the goal of this project, nor of draft-js.

The demo page might lead you to believe that this editor is both a source and rich-text editor because of the two input fields, but that is purely an implementation detail of the demo. The source <textarea> on the demo page is simply a plain textarea with no extra features and it's not part of React-RTE.

However, in the demo, when you use select some text in the composer and press bold, it \*should\* update the source code textarea below with \*\* around the words. But there is not a way to select text in the source textarea and use the toolbar to manipulate it.

I'm going to close this task as "not on roadmap" but please let me know if I've misunderstood your feature request. Thanks!

**Comment by mshick** [comment]
No, that's what I was curious about. I've played with the various markdown projects, my main issue is just bloat — bundling in the this + draft.js deps + something totally separate for markdown, even though this editor / draft.js seems to be about 90% of the way to supporting markdown as well. Maybe it just looks what way, but isn't really as close as I imagine.
