### ISSUE TITLE
some features I will have to implement

### ISSUE THREAD

**Issue by reharik** [sstur/react-rte#99]
Hi, at work they need these following features.  If I can't get them up and running in react-rte they will use tinymce.  Obviously I'm going to make this happen.  I plan to use blockStyleFn, setInlineStyleOverride, RichUtils, or whatever I can find to scrape it together.
I'm not saying I will get all these features implmented, or that I'll be able to do it in a way that will meet your standards ( but hopefully ).  I'm just saying this is the path I'm going down, and if anyone is already on this path for some of these and wants to share please let me know.  I'll try and report here my progress.

oh, and what they want is/are buttons for this functionality, just like tinymce, so some of this func exists but if you can't push a button these people are lost.

alignleft
aligncenter
alignright
alignjustify
fontselect
fontsizeselect
cut
copy
paste
outdent
indent
forecolor
backcolor
spellchecker

**Comment by sstur** [comment]
Hi @reharik! Thanks for making the world a better place by not using TinyMCE! I am happy to hear that you will use React RTE and contribute to this project. Let's make these features happen!

Some of these will be easier than other. alignleft, aligncenter, alignright, alignjustify will not be too difficult and those are already on my roadmap (we were waiting for an upstream change to Draft allowing us to store meta data on ContentBlock which has recently landed).

I think buttons for cut, copy, paste will be pretty easy. indent and outdent are implemented for list items (needs buttons) but for other blocks it can be similar to alignment by adding some indent value to the ContentBlock meta data.

forecolor and backcolor will need to work at the entity level, but should be reasonably doable. Similarly fontselect and fontsize will need to be at the entity level and you might want a custom dropdown in the toolbar or modal for the font selection. The UI there might me the more difficult part.

Lastly, spellchecker will be a challenge. Currently we are using the browser's built-in spellchecker which I feel is the right thing to do. But it does not allow us any control over spellcheck because there is no browser API for that feature. So you won't get any toolbar buttons for that unless you completely re-implement spellcheck using an HTTP service. That is how CKEditor has done it and I don't really like that approach. For one, it requires connectivity. It departs from the normal browser behavior that people are used to. They also override right-click menu to work with their spellcheck and that is not intuitive.

Anyway, what is your timeline for these features?

**Comment by sstur** [comment]
Update:

> toolbar buttons for cut, copy, paste; indent and outdent
this relates to #115

> forecolor and backcolor
this is more doable now since https://github.com/facebook/draft-js/issues/52 has been resolved.

**Comment by reharik** [comment]
great, we are still gonna do this, but seems i do research, then product
switches everything up and i don't get to do it till later.  But I think
we'll be on it soon.
Thanks f or the update,
r
